Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'app/assets/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'public/**/*'
    - 'node_modules/**/*'
    - config/initializers/devise.rb
    - config/initializers/simple_form_bootstrap.rb
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
  IgnoreCopDirectives: true
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Exclude:
    - '**/routes.rb'
    - config/environments/*
Metrics/AbcSize:
  Enabled: false
Rails/SkipsModelValidations:
  Blacklist:
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - toggle!
    - touch
    # - update_all
    - update_attribute
    - update_column
    # - update_columns
    - update_counters
